version: "3"

services:
  reverse-proxy:
    image: nginx
    container_name: "reverse-proxy"
    volumes:
      - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
    networks:
      - rp_nw

  app1:
    image: nginx
    container_name: "app1"
    volumes:
      - ./app1:/usr/share/nginx/html
    ports:
      - 3000:80
    networks:
      - rp_nw

  app2:
    image: nginx
    container_name: "app2"
    volumes:
      - ./app2:/usr/share/nginx/html
    ports:
      - 3001:80
    networks:
      - rp_nw

networks:
  rp_nw:
