version: "3"

services:
  load-balancer:
    image: nginx
    container_name: "load-balancer"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - lb_nw

  app1:
    image: nginx
    container_name: "app1"
    volumes:
      - ./app1:/usr/share/nginx/html
    ports:
      - 3000:80
    networks:
      - lb_nw

  app2:
    image: nginx
    container_name: "app2"
    volumes:
      - ./app2:/usr/share/nginx/html
    ports:
      - 3001:80
    networks:
      - lb_nw

networks:
  lb_nw:
