version: "3"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8088
    volumes:
      - ./html:/usr/share/nginx/html

volumes:
  nginx_data:
