# STACK-NAME: test-env-ec2
AWSTemplateFormatVersion: 2010-09-09
Description: EC2 template for test environment.

Parameters:
  VPCStack:
    Type: String
    Default: test-env-vpc
  EC2AMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  EC2WebServer01:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2AMI
      InstanceType: t2.micro
      SubnetId:
        Fn::ImportValue: !Sub ${VPCStack}-TestPrimaryWeb
      UserData: !Base64 |
        #! /bin/bash
        yum update -y
        yum -y install httpd

        chown apache:apache -R /var/www/html

        systemctl enable httpd.service
        systemctl start httpd.service
      SecurityGroupIds:
        - !Ref EC2SG
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: sg for web server
      VpcId:
        Fn::ImportValue: !Sub ${VPCStack}-VPCID
      SecurityGroupIngress: 
        - IpProtocol: tcp
          #CidrIp: 10.1.0.0/16
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80

Outputs:
  EC2WebServer01:
    Value: !Ref EC2WebServer01
    Export:
      Name: !Sub ${AWS::StackName}-EC2WebServer01

